include: package:strict_analyzer/analysis_options.yaml

linter:
  rules:
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false
    body_might_complete_normally_nullable: false
    avoid_redundant_argument_values: false

analyzer:
  strong-mode:
    implicit-dynamic: true

  errors:
    prefer_mixin: warning
