include: package:flutter_lints/flutter.yaml

linter:
  rules:
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false
    avoid_redundant_argument_values: false
    avoid_unnecessary_containers: false
    depend_on_referenced_packages: false
    library_private_types_in_public_api: false
    prefer_const_constructors: false
    prefer_const_constructors_in_immutables: false
    sized_box_for_whitespace: false
    sort_child_properties_last: false
    use_key_in_widget_constructors: false
    use_super_parameters: false

analyzer:
  strong-mode:
    implicit-dynamic: true

  errors:
    prefer_mixin: warning
